---
version: "2.1"
services:
  db:
      image: mysql
      container_name: learn-sql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: changeme
      ports: 
          - 3316:3306